# Generated by Django 3.0.4 on 2020-05-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Food', 'FOOD'), ('Auto', 'AUTO'), ('Entertainment', 'ENTERTAINMENT'), ('Home', 'HOME'), ('Personal', 'PERSONAL')], max_length=15, null=True, verbose_name='Choose a Category...'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='t_type',
            field=models.CharField(choices=[('Income', 'INCOME'), ('Expense', 'EXPENSE')], max_length=15, null=True, verbose_name='Choose a Transaction Type...'),
        ),
    ]
