# Generated by Django 2.2.12 on 2020-05-23 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='budgeting.Transaction')),
                ('trans_category', models.CharField(choices=[('Food', 'FOOD'), ('Auto', 'AUTO'), ('Entertainment', 'ENTERTAINMENT'), ('Home', 'HOME'), ('Personal', 'PERSONAL')], max_length=15, null=True, verbose_name='Category')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
            bases=('budgeting.transaction',),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='budgeting.Transaction')),
                ('trans_category', models.CharField(choices=[('Paycheck', 'PAYCHECK'), ('Transfer', 'TRANSFER'), ('Other Income', 'OTHER INCOME')], max_length=15, null=True, verbose_name='Category')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
            bases=('budgeting.transaction',),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Paycheck', 'PAYCHECK'), ('Transfer', 'TRANSFER'), ('Other Income', 'OTHER INCOME')], max_length=15, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(default='', max_length=30, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='t_type',
            field=models.CharField(default='', max_length=15, null=True, verbose_name='Deposit/Withdrawal'),
        ),
    ]
