# Generated by Django 3.0.4 on 2020-05-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_posted',
            field=models.DateField(verbose_name='Transaction\xa0Date (mm/dd/yyyy)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Information'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(max_length=30, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='t_type',
            field=models.CharField(max_length=15, null=True, verbose_name='Deposit/Withdrawal'),
        ),
    ]
