# Generated by Django 2.2.12 on 2020-05-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0002_auto_20200522_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(max_length=30, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='t_type',
            field=models.CharField(max_length=15, null=True, verbose_name='Deposit/Withdrawal'),
        ),
    ]
