# Generated by Django 3.0.4 on 2020-05-07 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgeting', '0002_auto_20200506_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='in_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_posted',
            field=models.DateField(null=True, verbose_name='Transaction\xa0Date'),
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Initial Balance')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_amount_gained', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_amount_spent', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('monthly_amount_gained', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('monthly_amount_spent', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('author', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
