# Generated by Django 3.0.4 on 2020-04-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0002_auto_20200426_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(max_length=30, verbose_name='Source (e.g. Part-time job, My Bank Account)'),
        ),
    ]
