# Generated by Django 2.2.12 on 2020-06-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0003_auto_20200512_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='author',
        ),
        migrations.RenameField(
            model_name='total',
            old_name='author',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
