# Generated by Django 2.2.12 on 2020-05-23 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0003_auto_20200522_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='transaction_ptr',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
