# Generated by Django 3.0.4 on 2020-05-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0003_auto_20200507_0111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_posted',
            field=models.DateField(null=True, verbose_name='Transaction\xa0Date (mm/dd/yyyy)'),
        ),
    ]
