# Generated by Django 2.2.12 on 2020-05-22 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgeting', '0003_auto_20200512_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Paycheck', 'PAYCHECK'), ('Transfer', 'TRANSFER'), ('Other Income', 'OTHER INCOME')], max_length=15, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(max_length=30, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='t_type',
            field=models.CharField(max_length=15, null=True, verbose_name='Deposit/Withdrawal'),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='budgeting.Transaction')),
                ('trans_category', models.CharField(choices=[('Paycheck', 'PAYCHECK'), ('Transfer', 'TRANSFER'), ('Other Income', 'OTHER INCOME')], max_length=15, null=True, verbose_name='Category')),
                ('income_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
            bases=('budgeting.transaction',),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='budgeting.Transaction')),
                ('trans_category', models.CharField(choices=[('Food', 'FOOD'), ('Auto', 'AUTO'), ('Entertainment', 'ENTERTAINMENT'), ('Home', 'HOME'), ('Personal', 'PERSONAL')], max_length=15, null=True, verbose_name='Category')),
                ('deposit_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
            bases=('budgeting.transaction',),
        ),
    ]
