# Generated by Django 2.2.12 on 2020-05-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0004_auto_20200522_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(max_length=15, null=True, verbose_name='Category'),
        ),
    ]
