# Generated by Django 3.0.4 on 2020-04-26 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0004_auto_20200426_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='author',
            new_name='user',
        ),
    ]
