# Generated by Django 3.0.4 on 2020-05-08 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0005_auto_20200507_1923'),
        ('budgeting', '0004_auto_20200507_2116'),
    ]

    operations = [
    ]
