# Generated by Django 3.0.4 on 2020-04-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0006_auto_20200426_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='t_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
