# Generated by Django 2.2.12 on 2020-05-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0006_auto_20200523_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='t_type',
            field=models.CharField(max_length=15, null=True, verbose_name='Expense/Withdrawal'),
        ),
    ]
