# Generated by Django 2.2.12 on 2020-05-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0008_auto_20200524_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='monthly_amount_gained',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='monthly_amount_spent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
