# Generated by Django 2.2.12 on 2020-05-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0009_auto_20200524_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='total',
            name='total_amount_gained',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='total',
            name='total_amount_spent',
            field=models.IntegerField(default=0),
        ),
    ]
